#! /bin/sh
bspc rule -r "*"

# AUTOSTART 
sxhkd -c $HOME/.config/bspwm/sxhkdrc &
# nitrogen --restore &
# polybar -r bar &
# picom &
# pidof bspswallow || bspswallow & # https://github.com/JopStro/bspswallow

# MONITORS
bspc monitor eDP1 -n 1 -d 1 2 3 4 5 6 7 8 9 
bspc monitor HDMI1 -n 0 -d 1 2 3 4 5 6 7 8 9 

# if there is more than one monitor you'll need to add more of these ^
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors  true

bspc config border_width         1
bspc config window_gap           0 

bspc config -m 0 top_padding 37 
bspc config -m 1 top_padding 37

# bspc config pointer_modifier mod4 
bspc config pointer_action1 move 
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config click_to_focus       true 

# colours 
bspc config normal_border_color		"#4c566a"
bspc config focused_border_color	"#d8dee9"
bspc config presel_feedback_color	"#d8dee9"

# RULES
bspc rule -a Zathura state=tiled
bspc rule -a Wrapper-2.0 state=floating center=true rectangle=960x625+0+0 border=off
bpsc rule -a emacs state=tiled 

# some programs need this (matlab/java)
wmname LG3D
